version: "3"
services:
  tyrell_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tyrell/tyrell_app
    container_name: tyrell_app
    tty: true
    restart: unless-stopped
    environment: 
      DB_HOST: tyrell_db
      DB_PASSWORD: tyrell
    volumes: 
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  tyrell_webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: tyrell/nginx
    container_name: tyrell_webserver
    restart: unless-stopped
    ports: 
      - "8088:80"
    volumes: 
      - ./:/var/www 
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on: 
      - tyrell_app
  
  tyrell_db:
    image: mysql:latest
    command:
      - "--default-authentication-plugin=mysql_native_password"
    container_name: tyrell_db
    restart: always
    environment: 
      MYSQL_DATABASE: tyrell
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: tyrell
    volumes: 
      - ./config/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - dbdata:/var/lib/mysql
    ports:
      - 33064:3306

volumes: 
  dbdata:
    driver: local

